name: ROS 2 Jazzy Workspace Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-ros2-workspace:
    runs-on: ubuntu-22.04
    steps:
    - uses: xanderhendriks/action-build-stm32cubeide@v10.0
      with:
        project: 'applications/sample_application/targets/STM32'
        build-target: 'sample_application/Debug'
